package com.alerdoci.ultimatepokedex.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF705D00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE171)
val md_theme_light_onPrimaryContainer = Color(0xFF221B00)
val md_theme_light_secondary = Color(0xFFC0000C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD5)
val md_theme_light_onSecondaryContainer = Color(0xFF410001)
val md_theme_light_tertiary = Color(0xFF006398)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001D31)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF030865)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF030865)
val md_theme_light_surfaceVariant = Color(0xFFEAE2CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4B4639)
val md_theme_light_outline = Color(0xFF7D7767)
val md_theme_light_inverseOnSurface = Color(0xFFF1EFFF)
val md_theme_light_inverseSurface = Color(0xFF1E2578)
val md_theme_light_inversePrimary = Color(0xFFE7C430)
val md_theme_light_surfaceTint = Color(0xFF705D00)
val md_theme_light_outlineVariant = Color(0xFFCEC6B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFE7C430)
val md_theme_dark_onPrimary = Color(0xFF3B2F00)
val md_theme_dark_primaryContainer = Color(0xFF554600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE171)
val md_theme_dark_secondary = Color(0xFFFFB4AA)
val md_theme_dark_onSecondary = Color(0xFF690003)
val md_theme_dark_secondaryContainer = Color(0xFF930006)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD5)
val md_theme_dark_tertiary = Color(0xFF93CCFF)
val md_theme_dark_onTertiary = Color(0xFF003351)
val md_theme_dark_tertiaryContainer = Color(0xFF004B73)
val md_theme_dark_onTertiaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF030865)
val md_theme_dark_onBackground = Color(0xFFE0E0FF)
val md_theme_dark_surface = Color(0xFF030865)
val md_theme_dark_onSurface = Color(0xFFE0E0FF)
val md_theme_dark_surfaceVariant = Color(0xFF4B4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC6B4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_inverseOnSurface = Color(0xFF030865)
val md_theme_dark_inverseSurface = Color(0xFFE0E0FF)
val md_theme_dark_inversePrimary = Color(0xFF705D00)
val md_theme_dark_surfaceTint = Color(0xFFE7C430)
val md_theme_dark_outlineVariant = Color(0xFF4B4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFBD743)